import type { Metadata } from "next";
import { brand, siteUrl } from "@/config/brand";
import { routes, type RouteKey } from "@/config/routes";
import type { Locale } from "@/i18n/locales";

type PageMetaInput = {
  locale: Locale;
  title?: string;
  description?: string;
  /** Route the page belongs to; drives canonical + hreflang alternates. */
  route?: RouteKey;
  /** Explicit path (without locale) for dynamic pages such as blog posts. */
  path?: string;
  /** Locales the page exists in, when not derivable from `route`. */
  availableLocales?: readonly Locale[];
  noIndex?: boolean;
};

/**
 * Builds page metadata. The brand name comes from brand settings via the
 * root title template, never from page copy (BR-WEB-002).
 */
export function pageMetadata({ locale, title, description, route, path, availableLocales, noIndex }: PageMetaInput): Metadata {
  const pagePath = path ?? (route ? routes[route].path : "");
  const localesForPage = availableLocales ?? (route ? routes[route].locales : [locale]);
  const languages: Record<string, string> = {};
  for (const l of localesForPage) languages[l] = `${siteUrl}/${l}${pagePath}`;
  if (localesForPage.includes("en")) languages["x-default"] = `${siteUrl}/en${pagePath}`;

  const resolvedDescription = description ?? brand.defaultDescription[locale] ?? brand.defaultDescription.en;
  // Page-level openGraph replaces the segment's file-based image, so name it explicitly.
  const shareImage = { url: `/${locale}/opengraph-image`, width: 1200, height: 630, alt: brand.name };

  return {
    title,
    description: resolvedDescription,
    alternates: {
      canonical: `${siteUrl}/${locale}${pagePath}`,
      languages,
    },
    openGraph: {
      title: title ? `${title} — ${brand.name}` : brand.name,
      description: resolvedDescription,
      url: `${siteUrl}/${locale}${pagePath}`,
      siteName: brand.name,
      locale: locale === "ar" ? "ar_SA" : "en_US",
      type: "website",
      images: [shareImage],
    },
    // The share image itself is generated by app/[locale]/opengraph-image.tsx.
    twitter: {
      card: "summary_large_image",
      images: [shareImage],
      title: title ? `${title} — ${brand.name}` : brand.name,
      description: resolvedDescription,
    },
    robots: noIndex ? { index: false, follow: true } : undefined,
  };
}
